openapi: 3.0.3

info:
  title: Resource Server API
  version: '1.0'

servers:
  - url: http://localhost:8080/v1

paths:
  /pets:
    get:
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pets"
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '201':
          description: Created

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
    oauth2:
      type: oauth2
      flows:
        clientCredentials: # <---- OAuth flow(authorizationCode, implicit, password or clientCredentials)
          tokenUrl: http://localhost:8180/realms/athena/protocol/openid-connect/token
          scopes: {}

  schemas:
    Pet:
      properties:
        id:
          type: integer
          example: 1234
        name:
          type: string
          example: snoopy
        type:
          type: string
          enum:
            - dog
            - cat
            - fish
          example: dog

    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"

security:
  - bearerAuth: []
  - oauth2: []
